spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/RentACarApplication
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Kkoc0312
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/kadir-car-rental-app
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
    jwt:
      auth:
        resource-id: kadir-car-rental-app
        principle-attribute: preferred_username

server:
  port: 8081
